### ISSUE TITLE
This project doesn't seem to be maintained ! Is there anyone here ?

### ISSUE THREAD

**Issue by frenchdevartist** [smileinnovation/cryptocurrency-trading#5]
Hi,
This project is very interesting but no one seems to work on it. Is there anyone interested to make it works ?

**Comment by kuty22** [comment]
Hello, this project was only an example. It hasn’t the goal to be continued. It was just to illustrate the article "How to make profits in cryptocurrency trading with machine learning".
(https://medium.com/smileinnovation/how-to-make-profits-in-cryptocurrency-trading-with-machine-learning-edb7ea33cee4)
