### ISSUE TITLE
moy_prev_day variable

### ISSUE THREAD

**Issue by LabDig** [smileinnovation/cryptocurrency-trading#6]
Dear Developer.
First of all, congratulations on your work.

I am interested in implementing your code on my daytrade bitcoin robot.

I'm from Brazil and I trade bitcoin at MercadoBitcoin exchange.
So, to get the data series I need to understand what is "moy_prev_day" variable. The variable "ask", "bid", "high", "low" is ok.
I read all code Scroller_bittrex_websocket_node, but not understand what is moy_prev_day" variable.
Can you help me?

Thank you very much in advance

**Comment by kuty22** [comment]
Dear LabDig,

Thanks!

This variable means the average value on the last 24 hours. It's coming from Bittrex.

Regards,

**Comment by LabDig** [comment]
I understand now. Tanks!
